### ISSUE TITLE
Remove config override tests after service startup when using config provider

### ISSUE THREAD

**Issue by farshidtz** [canonical/edgex-snap-testing#172]
As expected by [#4448](https://github.com/edgexfoundry/edgex-go/issues/4448), the snap tests have started failing since [this change](https://github.com/edgexfoundry/edgex-go/pull/4449) because the overrides no longer apply on top of configurations coming from config provider: `Common configuration loaded from the Configuration Provider. No overrides applied`

Need to change the snap tests to no longer test that, or make the services [run without config provider](https://docs.edgexfoundry.org/3.0/microservices/configuration/CommonEnvironmentVariables/#edgex_config_provider).

Failing test result:
```
=== RUN   TestChangeStartupMsg_app
    config_test.go:26: Set and verify new startup message: snap-testing (app)
    exec.go:19: [exec] sudo snap set edgexfoundry apps.support-scheduler.config.service-startupmsg='snap-testing (app)'
    exec.go:19: [exec] sudo snap restart edgexfoundry.support-scheduler
    exec.go:101: [stdout] 2023-03-16T14:24:06Z INFO Waiting for "snap.edgexfoundry.support-scheduler.service" to stop.
    exec.go:101: [stdout] Restarted.
    net.go:132: Retry 1/180: Waiting for ports: 59880 (core-data), 59881 (core-metadata), 59882 (core-command), 8200 (vault), 8500 (consul), [63](https://github.com/edgexfoundry/edgex-go/actions/runs/4431591455/jobs/7788709103?pr=4449#step:2:67)79 (redis)
    config_test.go:109: Retry 1/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 2/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 3/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 4/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 5/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 6/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 7/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 8/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 9/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:109: Retry 10/10: Waiting for startup message: snap-testing (app)
    exec.go:19: [exec] sudo journalctl --since "2023-03-16 14:24:05" --no-pager | grep "edgexfoundry.support-scheduler"|| true
    config_test.go:118: Time out: reached max 10 retries.
    config_test.go:31: 
        	Error Trace:	/home/runner/work/_actions/canonical/edgex-snap-testing/v3/test/suites/edgexfoundry/config_test.go:31
        	Error:      	Should be true
        	Test:       	TestChangeStartupMsg_app
        	Messages:   	new startup message = snap-testing (app)
```

**Comment by MonicaisHer** [comment]
I am unable to reproduce the issue using the services: 

- support-scheduler
- core-data
example:
```
snap install edgexfoundry --edge
sudo snap set edgexfoundry apps.support-scheduler.config.service-startupmsg='manul-snap-testing (app)'
sudo snap restart edgexfoundry.support-scheduler
```

```
app=support-scheduler source=config.go:143 msg="Common configuration loaded from the Configuration Provider. No overrides applied"
...
app=support-scheduler source=variables.go:389 msg="Variables override of 'Service.StartupMsg' by environment variable: SERVICE_STARTUPMSG=snap-testing (app)"
app=support-scheduler source=config.go:203 msg="Configuration has been pushed to into Configuration Provider with overrides applied"
...
app=support-scheduler source=message.go:51 msg="Starting support-scheduler 3.0.0-dev.104 "
app=support-scheduler source=message.go:55 msg="manul-snap-testing (app)"
```

but I am able to reproduce it using services:
- core-command

**Comment by MonicaisHer** [comment]
It appears that the behavior of the support-scheduler differs from core-data:
```
$ snap install edgexfoundry --edge
edgexfoundry (edge) 3.0.0-dev.114 from Canonical✓ installed
$ sudo snap set edgexfoundry apps.support-scheduler.config.edgex-config-provider='none'
$ sudo snap set edgexfoundry apps.support-scheduler.config.edgex-common-config=./config/core-common-config-bootstrapper/res/configuration.yaml
$ sudo snap set edgexfoundry apps.support-scheduler.config.service-startupmsg='manual-snap-testing'
$ snap restart edgexfoundry.support-scheduler
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: level=INFO ts=2023-03-27T12:12:08.477072763Z app=support-scheduler source=variables.go:457 msg="Variables override of 'Configuration Provider Information' by environment variable: EDGEX_CONFIG_PROVIDER=none"
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: level=INFO ts=2023-03-27T12:12:08.477078788Z app=support-scheduler source=variables.go:457 msg="Variables override of '-cc/--commonConfig' by environment variable: EDGEX_COMMON_CONFIG=./config/core-common-config-bootstrapper/res/configuration.yaml"
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: level=INFO ts=2023-03-27T12:12:08.477083724Z app=support-scheduler source=config.go:565 msg="Loading configuration file from ./config/core-common-config-bootstrapper/res/configuration.yaml"
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: level=INFO ts=2023-03-27T12:12:08.477120676Z app=support-scheduler source=secrets.go:277 msg="kick off token renewal with interval: 30m0s"
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: panic: runtime error: invalid memory address or nil pointer dereference
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x855b9f]
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: goroutine 1 [running]:
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/environment.(*Variables).buildPaths(0xc88ae0?, 0xc0004a05e8?)
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/go-mod-bootstrap/v3@v3.0.0-dev.56/bootstrap/environment/variables.go:236 +0x11f
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/environment.(*Variables).OverrideConfigMapValues(0xc000012888, 0x638?)
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/go-mod-bootstrap/v3@v3.0.0-dev.56/bootstrap/environment/variables.go:149 +0x3e
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/environment.(*Variables).OverrideConfiguration(0xc00053a000?, {0xd753a0, 0xc0004a0000})
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/go-mod-bootstrap/v3@v3.0.0-dev.56/bootstrap/environment/variables.go:130 +0x14f
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap/config.(*Processor).Process(0xc00053a000, {0xdef17d, 0x11}, {0xde1d61, 0x5}, {0xde7534, 0x8}, {0xf184d8, 0xc0004a0000}, {0xf1a8a0, ...})
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/go-mod-bootstrap/v3@v3.0.0-dev.56/bootstrap/config/config.go:188 +0x765
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap.RunAndReturnWaitGroup({0xf12fd8, 0xc000408e10}, 0xc000484900, {0xf18538?, 0xc0004903f0}, {0xdef17d, 0x11}, {0xde7534, 0x8}, {0xf184d8, ...}, ...)
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/go-mod-bootstrap/v3@v3.0.0-dev.56/bootstrap/bootstrap.go:126 +0x4ac
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: github.com/edgexfoundry/go-mod-bootstrap/v3/bootstrap.Run({0xf12fd8?, 0xc000408e10?}, 0xc000484900, {0xf18538?, 0xc0004903f0?}, {0xdef17d?, 0x0?}, {0xde7534?, 0x0?}, {0xf184d8, ...}, ...)
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/go-mod-bootstrap/v3@v3.0.0-dev.56/bootstrap/bootstrap.go:215 +0x11d
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: github.com/edgexfoundry/edgex-go/internal/support/scheduler.Main({0xf12fd8, 0xc000408e10}, 0x405c31?, 0xc000001ec0)
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/edgex-go/internal/support/scheduler/main.go:61 +0x73c
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]: main.main()
Mär 27 14:12:08 ubuntu edgexfoundry.support-scheduler[16559]:         github.com/edgexfoundry/edgex-go/cmd/support-scheduler/main.go:27 +0x89
Mär 27 14:12:08 ubuntu systemd[1]: snap.edgexfoundry.support-scheduler.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mär 27 14:12:08 ubuntu systemd[1]: snap.edgexfoundry.support-scheduler.service: Failed with result 'exit-code'.
```

**Comment by farshidtz** [comment]
@MonicaisHer please report the bug at https://github.com/edgexfoundry/go-mod-bootstrap

**Comment by MonicaisHer** [comment]
@farshidtz sure, reported: https://github.com/edgexfoundry/go-mod-bootstrap/issues/494
